Script started on 2017年03月13日 (週一) 10時04分03秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami;pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config l
error: key does not contain a section: l
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config l-l
user.email=believe861014@gmail.com
user.name=JCP1014
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone https://github.com/JCP1014/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m exit

Script done on 2017年03月13日 (週一) 10時04分59秒
