Script started on 2017年03月13日 (週一) 10時23分28秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m ./A
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m git clone https:// [Kgithub.com/JCP1014/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 11, done.[K
remote: Compressing objects:  12% (1/8)   [Kremote: Compressing objects:  25% (2/8)   [Kremote: Compressing objects:  37% (3/8)   [Kremote: Compressing objects:  50% (4/8)   [Kremote: Compressing objects:  62% (5/8)   [Kremote: Compressing objects:  75% (6/8)   [Kremote: Compressing objects:  87% (7/8)   [Kremote: Compressing objects: 100% (8/8)   [Kremote: Compressing objects: 100% (8/8), done.[K
remote: Total 11 (delta 0), reused 11 (delta 0), pack-reused 0[K
Unpacking objects:   9% (1/11)   Unpacking objects:  18% (2/11)   Unpacking objects:  27% (3/11)   Unpacking objects:  36% (4/11)   Unpacking objects:  45% (5/11)   Unpacking objects:  54% (6/11)   Unpacking objects:  63% (7/11)   Unpacking objects:  72% (8/11)   Unpacking objects:  81% (9/11)   Unpacking objects:  90% (10/11)   Unpacking objects: 100% (11/11)   Unpacking objects: 100% (11/11), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m exit

Script done on 2017年03月13日 (週一) 10時26分07秒
